# Site settings
title: "Resume Of Zaman-A-Piri Pasa"
description: "Web Application Developer"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Zaman-A-Piri Pasa"
resume_title:                   "Web Application Developer"
resume_contact_email:           "pollobcse05@gmail.com"
resume_contact_telephone:       "+8801723084619"
resume_contact_address:         "Dhaka, Bangladesh"
resume_header_contact_info: "Dhaka, Bangladesh | +8801723084619 | pollobcse05@gmail.com"
resume_header_intro: "<p>An accomplished web application developer with 7+ years strong experience in all stages of Web based development lifecycle, from concept and development through quality assurance (QA) and tuning. Extensive experience in designing and implementation of large-scale enterprise application by following Agile/CMMI methodology. <br/><br/>Highly motivated and innovative in finding solution for problem. I love to program things that work in real world and useful for people in their business. Proficient in designing, analyzing, developing web based application in LAMP stack.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_linkedin_url:          "https://linkedin.com/in/piripasa"
  resume_github_url:            "https://github.com/piripasa"
  resume_twitter_url:           "https://twitter.com/piripasa"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://facebook.com/piripasa"
  resume_instagram_url:         "http://instagram.com/piripasa"
  # resume_website_url:           "http://joelglovier.com"
resume_print_social_links:      false

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
